name: Add StreamTV Content to a Skylark Account
on:
  workflow_dispatch:
    inputs:
      skylark_url:
        type: string
        default: https://api.saas-sl-develop-10.skylark-dev.skylarkplatform.io/graphql
        required: true
        description: Your Skylark's GraphQL URL, should end with /graphql. Default to sl-develop-10's URL.
      skylark_api_key:
        type: string
        required: true
        description: Your Skylark API Key.
      ingest_chunk_size:
        type: string
        required: false
        description: The number of objects to create/update in a single request.
concurrency:
  group: ingest-streamtv-content-${{ github.event.inputs.skylark_url }}
  cancel-in-progress: true
jobs:
  ingestor:
    name: Ingest StreamTV Content
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Mask API key input
        id: add_mask
        run: |
          API_KEY=$(cat $GITHUB_EVENT_PATH | jq -r '.inputs.skylark_api_key' )
          echo ::add-mask::$API_KEY
          echo SKYLARK_API_KEY="$API_KEY" >> $GITHUB_ENV
      - uses: ./.github/actions/run-ingestor
        with:
          airtable-api-key: ${{ secrets.AIRTABLE_API_KEY }}
          airtable-base-id: ${{ secrets.AIRTABLE_BASE_ID }}
          skylark-api-url: ${{ github.event.inputs.skylark_url }}
          create-additional-objects: "true"
          saas-ingest: "true"
          saas-api-token: ${{ env.SKYLARK_API_KEY }}
          content-type: "streamtv"
          ingest-chunk-size: ${{ github.event.inputs.ingest_chunk_size }}
