name: Pull Request Checks
on:
  pull_request:
  push:
    branches:
      - main
concurrency:
  group: pr-checks-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint, Prettier & Jest
    steps:
      - uses: actions/checkout@v4.4.0
      - uses: actions/setup-node@v4.4.0
        with:
          node-version: 18.20.8
          cache: yarn
      - run: yarn
      - run: yarn tsc:all
      - run: yarn lint:all
      - run: yarn prettier:check
      - run: yarn test:ci
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v5.5.5
      - name: Test Report
        uses: dorny/test-reporter@v1.9.1
        if: success() || failure()
        with:
          name: Frontend Unit Test Results
          path: "!(node_modules)/**/reports/jest-junit.xml"
          reporter: jest-junit
